# Database Settings
db:
  type: "mariadb" # Available types: "hsqldb", "h2", "mysql", "mariadb"
  prefix: "alathra_skills_" # The table prefix
  host: "127.0.0.1"
  port: 3306
  database: "alathra"
  user: "root"
  pass: ""
  repair: false
